@local = http://localhost:3900
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmU1OTMzZGFmZjBhNjZjZDdlMDM5OTgiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY1OTIxMzE0N30.T2CfnQQh_P8UaEPpr_JshcwlLYb5vH1r4tY_81P2rN0

@token2 =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmU1OTg3Y2EwZmRjODAyZTA0MjYxZGMiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY1OTI2NTg1M30.LcuKhtKrjxsY6eu52o7nLtWWN-9zG2ja56HWmRCo5aI

@token3 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmU2NmNmMTliZWU1Mjk2N2Q0NGZiOGQiLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY1OTI2ODYzMX0.Zz6G_bOvi4NX5CS77T4BxJtf2EckXvbhBHCPSkNXovU
### register user
POST {{local}}/api/users
Content-Type: application/json

{
    "name":"shusi",
    "email":"shusi1@gmail.com",
    "password": "123456"
}

### me
GET {{local}}/api/users/me
x-auth-token: {{token3}}

### sign in
POST {{local}}/api/auth
Content-Type: application/json

{
    "email":"shusi@gmail.com",
    "password": "123456"
}

### friends
GET {{local}}/api/users/friends
x-auth-token: {{token}}

### add friend ### ask daniel put-get
PUT {{local}}/api/users/friends/add/62e66cf19bee52967d44fb8d
x-auth-token: {{token}}


### remove friend ### ask daniel put-get
PUT {{local}}/api/users/friends/remove/62e66cf19bee52967d44fb8d
x-auth-token: {{token}}

### get all
GET {{local}}/api/users/users
x-auth-token: {{token}}

### get user
GET {{local}}/api/users/62e66cf19bee52967d44fb8d
x-auth-token:{{token}}